### ISSUE TITLE
EPIC > Website

### ISSUE THREAD

**Issue by maurerbot** [kubelt/kubelt.com#1]
# Why
Kubelt needs a fresh website that makes our value prop POP right off the page.

# What
A tailwind powered website

# How
- [ ] CHORE(kubelt.com) > Setup kubelt.com repo
- [ ] CHORE(kubelt.com) > Setup GH pages for web2
- [ ] CHORE(kubelt.com)  > Setup publish-web3 for IPNS site
- [ ] FEAT(kubelt.com) >  Website Layout
- [ ] FEAT(kubelt.com) > Website Content
- [ ] FEAT(kubelt.com) > Website Assets

# Notes
Some inspiration:
- https://autocode.com/
